baseURL = "https://nathaliagg.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
author = "Nathalia Graf-Grachet"
title = "Nathalia Graf-Grachet"
# description = "Call me Jane"
profilePicture = "images/profile.png"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/nathaliagg"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@alexbilz.com"

## Menu items

[menu]

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/about/"

  [[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "CV/Resume"
  weight = 300
  identifier = "cv"
  url = "/cv/"
